"use client";
import "@xyflow/react/dist/style.css";
import { Background, Controls, Handle, MiniMap, Position, ReactFlow, addEdge, applyEdgeChanges, applyNodeChanges, type Connection, type Edge, type EdgeChange, type Node, type NodeChange, type NodeProps } from "@xyflow/react";
import { Bot, Clock3, GitBranch, Globe2, MessageSquareText, Play, Save, Upload } from "lucide-react";
import { DragEvent, useEffect, useMemo, useState } from "react";
import * as api from "@/lib/workflow-api";

type FlowData={label:string;triggerType?:string;seconds?:number;field?:string;operator?:string;value?:string;url?:string;method?:string;body?:string;phoneNumberId?:string;recipient?:string};
const starterNodes:Node<FlowData>[]=[{id:"trigger-1",type:"trigger",position:{x:60,y:160},data:{label:"Inbound message",triggerType:"inbound_message"}},{id:"condition-1",type:"condition",position:{x:360,y:150},data:{label:"Contains hello",field:"/message/body",operator:"contains",value:"hello"}},{id:"send-1",type:"whatsapp_text",position:{x:680,y:80},data:{label:"Reply",body:"Thanks for messaging us, {{message.from}}"}},{id:"delay-1",type:"delay",position:{x:680,y:270},data:{label:"Wait",seconds:300}}];
const starterEdges:Edge[]=[{id:"e-trigger-condition",source:"trigger-1",target:"condition-1"},{id:"e-yes-send",source:"condition-1",sourceHandle:"true",target:"send-1",data:{branch:"true"}},{id:"e-no-delay",source:"condition-1",sourceHandle:"false",target:"delay-1",data:{branch:"false"}}];
const palettes=[["trigger","Inbound trigger",Play],["condition","Condition",GitBranch],["delay","Delay",Clock3],["webhook","Webhook",Globe2],["whatsapp_text","WhatsApp text",MessageSquareText],["ai_future","AI placeholder",Bot]] as const;
export function WorkflowBuilder(){const [nodes,setNodes]=useState(starterNodes);const [edges,setEdges]=useState(starterEdges);const [selected,setSelected]=useState<string|null>("condition-1");const [items,setItems]=useState<api.Workflow[]>([]);const [workflowId,setWorkflowId]=useState<number|null>(null);const [history,setHistory]=useState<api.WorkflowExecution[]>([]);const [versions,setVersions]=useState<api.WorkflowVersion[]>([]);const [stats,setStats]=useState<api.WorkflowAnalytics|null>(null);const [notice,setNotice]=useState("Draft ready");
 useEffect(()=>{void api.workflows().then(setItems).catch(()=>setNotice("Backend workflow API unavailable"));},[]);
 const chosen=nodes.find(n=>n.id===selected); const nodeTypes=useMemo(()=>({trigger:FlowNode,condition:FlowNode,delay:FlowNode,webhook:FlowNode,whatsapp_text:FlowNode,ai_future:FlowNode}),[]);
 function graph(){return {nodes,edges};} async function create(){try{const v=await api.createWorkflow(graph());setWorkflowId(v.workflowId);setVersions([v]);setNotice("Workflow created");setItems(await api.workflows());}catch{setNotice("Create failed");}}
 async function save(){if(!workflowId)return create();try{const v=await api.saveDraft(workflowId,graph());setVersions(list=>[v,...list.filter(x=>x.id!==v.id)]);setNotice("Draft saved");}catch{setNotice("Save failed");}}
 async function publish(){if(!workflowId)return;try{await api.publish(workflowId);setNotice("Published");await refresh(workflowId);}catch{setNotice("Publish failed: graph needs connected supported nodes");}}
 async function refresh(id:number){setWorkflowId(id);const [v,h,a]=await Promise.all([api.versions(id),api.executions(id),api.analytics(id)]);setVersions(v);setHistory(h);setStats(a);if(v[0]){const g=JSON.parse(v[0].graphJson) as {nodes:Node<FlowData>[];edges:Edge[]};setNodes(g.nodes);setEdges(g.edges);}}
 function drop(event:DragEvent){event.preventDefault();const type=event.dataTransfer.getData("application/workflow-node");if(!type)return;const id=`${type}-${crypto.randomUUID()}`;setNodes(list=>[...list,{id,type,position:{x:event.clientX-300,y:event.clientY-120},data:defaults(type)}]);setSelected(id);}
 function change(key:keyof FlowData,value:string){setNodes(list=>list.map(n=>n.id===selected?{...n,data:{...n.data,[key]:key==="seconds"?Number(value):value}}:n));}
 return <main className="grid h-dvh grid-cols-[250px_minmax(0,1fr)_340px] bg-[#f4f7f6] text-[#12201a]"><aside className="border-r border-[#d6ddd9] bg-white p-4"><h1 className="text-xl font-semibold">Flow Builder</h1><div className="mt-4 flex gap-2"><button className="tool" onClick={()=>void save()}><Save/>Save</button><button className="tool" onClick={()=>void publish()}><Upload/>Publish</button></div><p className="mt-3 text-sm text-[#53625b]">{notice}</p><h2 className="mt-6 text-sm font-semibold">Nodes</h2><div className="mt-2 grid gap-2">{palettes.map(([type,label,Icon])=><button draggable onDragStart={e=>e.dataTransfer.setData("application/workflow-node",type)} key={type} className="flex h-11 items-center gap-2 rounded border border-[#d6ddd9] px-3 text-left text-sm"><Icon className="h-4 w-4"/>{label}</button>)}</div><h2 className="mt-6 text-sm font-semibold">Workflows</h2><div className="mt-2 grid gap-1">{items.map(w=><button key={w.id} onClick={()=>void refresh(w.id)} className={`truncate rounded px-2 py-2 text-left text-sm ${w.id===workflowId?"bg-[#dff6ef]":"hover:bg-[#eef3f1]"}`}>{w.name}</button>)}</div></aside><section onDragOver={e=>e.preventDefault()} onDrop={drop}><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodeClick={(_,n)=>setSelected(n.id)} onNodesChange={(c:NodeChange<Node<FlowData>>[])=>setNodes(n=>applyNodeChanges(c,n))} onEdgesChange={(c:EdgeChange<Edge>[])=>setEdges(e=>applyEdgeChanges(c,e))} onConnect={(c:Connection)=>setEdges(e=>addEdge({...c,data:{branch:c.sourceHandle}},e))} fitView><Background/><Controls/><MiniMap/></ReactFlow></section><aside className="overflow-y-auto border-l border-[#d6ddd9] bg-white p-4"><Inspector node={chosen} onChange={change}/><section className="mt-6"><h2 className="font-semibold">Analytics</h2><p className="mt-2 text-sm">{stats?`${stats.completed}/${stats.executions} completed, ${stats.failed} failed, ${stats.waiting} waiting`:"Publish and load a workflow"}</p>{workflowId&&<button className="tool mt-3" onClick={()=>void api.testTrigger(workflowId).then(()=>refresh(workflowId))}><Play/>Test</button>}</section><section className="mt-6"><h2 className="font-semibold">Versions</h2>{versions.map(v=><p key={v.id} className="mt-1 text-sm">v{v.version} {v.publishedAt?"published":"draft"}</p>)}</section><section className="mt-6"><h2 className="font-semibold">History</h2>{history.slice(0,8).map(x=><p key={x.id} className="mt-2 rounded border border-[#e2e8e4] p-2 text-xs">{x.status} #{x.id} {x.currentNodeId}</p>)}</section></aside></main>}
function FlowNode({type,data}:NodeProps<Node<FlowData>>){return <div className="min-w-44 rounded-md border border-[#9eb8ae] bg-white p-3 shadow"><Handle type="target" position={Position.Left}/><b className="block text-sm">{data.label}</b><span className="text-xs text-[#53625b]">{type}</span>{type==="condition"?<><Handle id="true" type="source" position={Position.Right} style={{top:28}}/><Handle id="false" type="source" position={Position.Right} style={{top:58}}/></>:<Handle type="source" position={Position.Right}/>}</div>}
function Inspector({node,onChange}:{node:Node<FlowData>|undefined;onChange:(k:keyof FlowData,v:string)=>void}){if(!node)return <p>Select a node.</p>;return <section><h2 className="font-semibold">Node</h2><Input label="Label" value={node.data.label} onChange={v=>onChange("label",v)}/>{node.type==="condition"&&<><Input label="Field pointer" value={node.data.field??""} onChange={v=>onChange("field",v)}/><Input label="Operator" value={node.data.operator??""} onChange={v=>onChange("operator",v)}/><Input label="Value" value={node.data.value??""} onChange={v=>onChange("value",v)}/></>}{node.type==="delay"&&<Input label="Seconds" value={String(node.data.seconds??60)} onChange={v=>onChange("seconds",v)}/>} {node.type==="webhook"&&<><Input label="URL" value={node.data.url??""} onChange={v=>onChange("url",v)}/><Input label="Method" value={node.data.method??"POST"} onChange={v=>onChange("method",v)}/></>}{node.type==="whatsapp_text"&&<><Input label="Phone number id" value={node.data.phoneNumberId??""} onChange={v=>onChange("phoneNumberId",v)}/><Input label="Recipient" value={node.data.recipient??""} onChange={v=>onChange("recipient",v)}/><Input label="Body" value={node.data.body??""} onChange={v=>onChange("body",v)}/></>} {node.type==="ai_future"&&<p className="mt-3 text-sm text-[#53625b]">Reserved for a future policy-governed AI processor.</p>}</section>}
function Input({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="mt-3 block text-sm">{label}<input value={value} onChange={e=>onChange(e.target.value)} className="mt-1 h-9 w-full rounded border border-[#c7d0cb] px-2 outline-none focus:border-[#0b8068]"/></label>}
function defaults(type:string):FlowData{return ({trigger:{label:"Inbound",triggerType:"inbound_message"},condition:{label:"Condition",field:"/message/body",operator:"contains",value:""},delay:{label:"Delay",seconds:60},webhook:{label:"Webhook",url:"https://example.com/hook",method:"POST"},whatsapp_text:{label:"WhatsApp text",body:"Hello {{message.from}}"},ai_future:{label:"AI action"}} as Record<string,FlowData>)[type]??{label:type};}
