package com.whatsaas.automation.application;
import com.fasterxml.jackson.databind.*; import com.whatsaas.automation.application.dto.*; import com.whatsaas.automation.domain.*; import com.whatsaas.automation.infrastructure.*; import com.whatsaas.common.exception.DomainException; import com.whatsaas.common.tenant.TenantContext; import java.util.List; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class WorkflowAuthoringService{
 private final AutomationWorkflowRepository workflows; private final WorkflowVersionRepository versions; private final WorkflowExecutionRepository executions; private final WorkflowStepRepository steps; private final ObjectMapper mapper;
 public WorkflowAuthoringService(AutomationWorkflowRepository w,WorkflowVersionRepository v,WorkflowExecutionRepository e,WorkflowStepRepository s,ObjectMapper m){workflows=w;versions=v;executions=e;steps=s;mapper=m;}
 @Transactional public WorkflowVersionResponse create(WorkflowCreateRequest r){Long t=TenantContext.currentTenantId(); AutomationWorkflow w=workflows.save(new AutomationWorkflow(t,r.name().trim(),r.description())); return WorkflowVersionResponse.from(versions.save(new WorkflowVersion(w.getId(),t,w.getDraftVersion(),json(r.graph()))));}
 @Transactional public WorkflowVersionResponse save(Long id,WorkflowGraphRequest r){AutomationWorkflow w=workflow(id); WorkflowVersion v=versions.findByTenantIdAndWorkflowIdAndVersion(w.getTenantId(),id,w.getDraftVersion()).orElseGet(()->versions.save(new WorkflowVersion(id,w.getTenantId(),w.getDraftVersion(),json(r.graph())))); v.replaceGraph(json(r.graph())); return WorkflowVersionResponse.from(v);}
 @Transactional public WorkflowResponse publish(Long id){AutomationWorkflow w=workflow(id); WorkflowVersion draft=versions.findByTenantIdAndWorkflowIdAndVersion(w.getTenantId(),id,w.getDraftVersion()).orElseThrow(()->new DomainException(HttpStatus.CONFLICT,"WORKFLOW_DRAFT_MISSING","Workflow draft is missing.")); validate(draft.getGraphJson()); draft.publish(); w.publish(draft.getId()); w.advanceDraft(); versions.save(new WorkflowVersion(id,w.getTenantId(),w.getDraftVersion(),draft.getGraphJson())); return WorkflowResponse.from(w);}
 @Transactional(readOnly=true) public List<WorkflowResponse> list(){return workflows.findByTenantIdOrderByUpdatedAtDesc(TenantContext.currentTenantId()).stream().map(WorkflowResponse::from).toList();}
 @Transactional(readOnly=true) public List<WorkflowVersionResponse> versions(Long id){workflow(id);return versions.findByTenantIdAndWorkflowIdOrderByVersionDesc(TenantContext.currentTenantId(),id).stream().map(WorkflowVersionResponse::from).toList();}
 @Transactional(readOnly=true) public List<WorkflowExecutionResponse> history(Long id){workflow(id);return executions.findTop100ByTenantIdAndWorkflowIdOrderByStartedAtDesc(TenantContext.currentTenantId(),id).stream().map(WorkflowExecutionResponse::from).toList();}
 @Transactional(readOnly=true) public WorkflowAnalyticsResponse analytics(Long id){List<WorkflowExecution> all=executions.findTop100ByTenantIdAndWorkflowIdOrderByStartedAtDesc(TenantContext.currentTenantId(),id);return new WorkflowAnalyticsResponse(all.size(),all.stream().filter(e->e.getStatus()==WorkflowExecutionStatus.COMPLETED).count(),all.stream().filter(e->e.getStatus()==WorkflowExecutionStatus.FAILED).count(),all.stream().filter(e->e.getStatus()==WorkflowExecutionStatus.WAITING||e.getStatus()==WorkflowExecutionStatus.RETRY_WAIT).count());}
 @Transactional(readOnly=true) public List<WorkflowStepResponse> steps(Long executionId){executions.findByTenantIdAndId(TenantContext.currentTenantId(),executionId).orElseThrow(()->new DomainException(HttpStatus.NOT_FOUND,"WORKFLOW_EXECUTION_NOT_FOUND","Workflow execution not found."));return steps.findByExecutionIdOrderByStartedAtAsc(executionId).stream().map(WorkflowStepResponse::from).toList();}
 private AutomationWorkflow workflow(Long id){return workflows.findByTenantIdAndId(TenantContext.currentTenantId(),id).orElseThrow(()->new DomainException(HttpStatus.NOT_FOUND,"WORKFLOW_NOT_FOUND","Workflow not found."));}
 private String json(JsonNode n){try{return mapper.writeValueAsString(n);}catch(Exception e){throw new IllegalArgumentException("Workflow graph JSON invalid.",e);}}
 private void validate(String graph){try{JsonNode n=mapper.readTree(graph);if(!n.path("nodes").isArray()||!n.path("edges").isArray()||n.path("nodes").isEmpty())throw new Exception();}catch(Exception e){throw new DomainException(HttpStatus.BAD_REQUEST,"WORKFLOW_GRAPH_INVALID","Workflow graph must contain nodes and edges.");}}
}
