package com.whatsaas.automation.application;
import com.fasterxml.jackson.databind.*; import com.fasterxml.jackson.databind.node.ObjectNode; import com.whatsaas.automation.application.dto.WorkflowExecutionResponse; import com.whatsaas.automation.domain.*; import com.whatsaas.automation.engine.WorkflowExecutionEngine; import com.whatsaas.automation.infrastructure.*; import com.whatsaas.whatsapp.domain.WhatsAppMessage; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class WorkflowTriggerService{private final AutomationWorkflowRepository workflows;private final WorkflowVersionRepository versions;private final WorkflowExecutionRepository executions;private final WorkflowExecutionEngine engine;private final ObjectMapper mapper;public WorkflowTriggerService(AutomationWorkflowRepository w,WorkflowVersionRepository v,WorkflowExecutionRepository e,WorkflowExecutionEngine g,ObjectMapper m){workflows=w;versions=v;executions=e;engine=g;mapper=m;}
 @Transactional public List<WorkflowExecutionResponse> inbound(WhatsAppMessage message){ObjectNode c=mapper.createObjectNode();ObjectNode m=c.putObject("message");m.put("id",message.getId());m.put("from",message.getRecipient());m.put("phoneNumberId",message.getPhoneNumberId());m.put("body",message.getBody());return startActive(message.getTenantId(),"inbound_message",c);}
 @Transactional public WorkflowExecutionResponse manual(Long tenantId,Long workflowId,JsonNode context){AutomationWorkflow w=workflows.findByTenantIdAndId(tenantId,workflowId).orElseThrow();return start(w,"manual",context);}
 private List<WorkflowExecutionResponse> startActive(Long tenant,String trigger,JsonNode context){return workflows.findByTenantIdAndActiveTrue(tenant).stream().filter(w->hasTrigger(w,trigger)).map(w->start(w,trigger,context)).toList();}
 private WorkflowExecutionResponse start(AutomationWorkflow w,String trigger,JsonNode context){WorkflowVersion v=versions.findById(w.getPublishedVersionId()).orElseThrow();WorkflowExecution e=executions.save(new WorkflowExecution(w.getTenantId(),w.getId(),v.getId(),trigger,triggerNode(v.getGraphJson(),trigger),write(context)));engine.run(e);return WorkflowExecutionResponse.from(e);}
 private boolean hasTrigger(AutomationWorkflow w,String trigger){return triggerNode(versions.findById(w.getPublishedVersionId()).orElseThrow().getGraphJson(),trigger)!=null;} private String triggerNode(String graph,String trigger){try{for(JsonNode n:mapper.readTree(graph).path("nodes"))if("trigger".equals(n.path("type").asText())&&trigger.equals(n.path("data").path("triggerType").asText("inbound_message")))return n.path("id").asText();return null;}catch(Exception e){throw new IllegalArgumentException("Workflow graph invalid.",e);}} private String write(JsonNode n){try{return mapper.writeValueAsString(n);}catch(Exception e){throw new IllegalArgumentException("Context invalid.",e);}}
}
